// src/js/constants/action-types.js
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const TITLE_FORBIDDEN = "TITLE_FORBIDDEN";

//SIGN UP
export const UPDATE_DATA_INPUT_SIGNUP = "UPDATE_DATA_INPUT_SIGNUP";

//LOGIN
export const UPDATE_DATA_INPUT_LOGIN = "UPDATE_DATA_INPUT_LOGIN";