// src/js/constants/action-types.js
export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const TITLE_FORBIDDEN = "TITLE_FORBIDDEN";

//SIGN UP
export const UPDATE_DATA_INPUT_SIGNUP = "UPDATE_DATA_INPUT_SIGNUP";
export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

//LOGIN
export const UPDATE_DATA_INPUT_LOGIN = "UPDATE_DATA_INPUT_LOGIN";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//USER
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";

//REDIRECT
export const UPDATE_REDIRECT_DATA = "UPDATE_REDIRECT_DATA";

