//SIGN UP
export const UPDATE_DATA_INPUT_SIGNUP = "UPDATE_DATA_INPUT_SIGNUP"
export const SUBMIT_SIGNUP = "SUBMIT_SIGNUP"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

//LOGIN
export const UPDATE_DATA_INPUT_LOGIN = "UPDATE_DATA_INPUT_LOGIN"
export const USER_LOGIN = "USER_LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const GET_AUTH_DATA = "GET_AUTH_DATA"
export const VERIFY_TOKEN_FAILED = "VERIFY_TOKEN_FAILED"